server:
  port: 8080
spring:
  datasource:
    druid:
      web-stat-filter:
        enabled: true
        exclusions: "*.js,*.css,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        login-username: admin
        login-password: 123456
        allow: ""
      filter:
        stat:
          enabled: true
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
    dynamic:
      primary: master
      strict: false
      druid:
        initial-size: 1
        max-active: 400
        min-idle: 1
        max-wait: 6000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        validation-query: SELECT 1 FROM DUAL
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        use-global-datasource-stat: true
        filters: stat,wall,log4j2
        stat:
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 500
        wall:
          select-into-allow: false
          delete-allow: false
          update-allow: false
          insert-allow: false
          merge-allow: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver